language: android

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-26"
  - yes | sdkmanager "platforms;android-25"

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra

script:
- "./gradlew assembleDebug"
